# Generated by Django 4.0.6 on 2023-07-03 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazarcaridade', '0002_evento_usuario_item_descricao_item_preco_item_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descricao',
            new_name='descricao_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao_evento',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='nome_item',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
