# Generated by Django 4.0.6 on 2023-07-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazarcaridade', '0003_rename_descricao_item_descricao_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bazarcaridade.evento'),
        ),
    ]
